### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kernelcoffee** [kernelcoffee/SteamSelfGifter#4]
```
steamselfgifter    | Traceback (most recent call last):
steamselfgifter    |   File "/app/steamselfgifter.py", line 91, in <module>
steamselfgifter    |     games = get_games()
steamselfgifter    |   File "/app/steamselfgifter.py", line 69, in get_games
steamselfgifter    |     game = process_game(item)
steamselfgifter    |   File "/app/steamselfgifter.py", line 24, in process_game
steamselfgifter    |     game.set_steam_id(item.find("a", {"class": "giveaway__icon"})["href"])
steamselfgifter    | TypeError: 'NoneType' object is not subscriptable

```

**Comment by kernelcoffee** [comment]
Fixed with https://github.com/kernelcoffee/SteamSelfGifter/pull/5
